---
title: "timecourse 231 acute hypoxic response"
author: "Kate"
date: "2025-11_30"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(here)
library(janitor)
library(tximport)
library(tidyverse)
library(EnhancedVolcano)
library(msigdbr)
library(viridis)
library(gridExtra)
library(ggthemes)
library(ggrepel)
library(scales)
library(survival)
library(DESeq2)
library(limma)
library(clusterProfiler)
library(plotly)
library(ggokabeito)
library(ggvenn)
library(ggpubr)
library(DT)
library(edgeR)
library(cowplot)
library(ggExtra)
library(ggprism)
library(GeneOverlap)
library(writexl)
library(survminer)
library(readxl)
library(reshape2)
```

```{r}
source(here("code/functions.R"))
cat("Available functions: createNormMatrix, deFunction\n")
```

# Load data from timecourse_qc analysis

```{r load_data}
# Load count matrices
allCounts <- read_csv(here("output", "human_allCounts_raw.csv")) %>%
  column_to_rownames("gene_id")

normMatrix <- read_csv(here("output", "normalizedCounts.csv")) %>%
  column_to_rownames("gene_id")

spikein <- read_csv(here("output", "dros_spikeInCounts_raw.csv")) %>%
  column_to_rownames("gene_id")

top500_ids <- spikein %>%
  rownames_to_column("gene_id") %>%
  pull(gene_id)

cat("Loaded count matrices:\n")
cat("allCounts dimensions:", dim(allCounts), "\n")
cat("normMatrix dimensions:", dim(normMatrix), "\n")
cat("spikein dimensions:", dim(spikein), "\n")
cat("Number of spike-in genes:", length(top500_ids), "\n")
```

# Load DESeq results (with spike-in normalization)

```{r load_deseq_results}
# Load classified DESeq results for all timepoints
deseq_1hr <- read_csv(here("output", "deseq_results_1hr_spike.csv"))
deseq_4hr <- read_csv(here("output", "deseq_results_4hr_spike.csv"))
deseq_24hr <- read_csv(here("output", "deseq_results_24hr_spike.csv"))

cat("Loaded DESeq results:\n")
cat("1hr results:", nrow(deseq_1hr), "genes\n")
cat("4hr results:", nrow(deseq_4hr), "genes\n")
cat("24hr results:", nrow(deseq_24hr), "genes\n")

# Summary of significant genes per timepoint
cat("\n1hr significant genes:\n")
table(deseq_1hr$class)

cat("\n4hr significant genes:\n")
table(deseq_4hr$class)

cat("\n24hr significant genes:\n")
table(deseq_24hr$class)
```
