---
title: "Effect of knockdown on hypoxic response"
author: "Kate"
date: "2025-01-16"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(ggplot2)
library(ggExtra)
library(ggprism)
library(gridExtra)
library(cowplot)
```

# Effect of knockdown on hypoxic response

Read in deseq results

```{r}
#sictrl
hyp_response_deseq_1hr <-read_csv(here("output", "translation_categories_1hr.csv")) |>
  dplyr::select(gene_id, te_lfc, te_padj) |>
  rename(sictrl_1hr_te_lfc = te_lfc, sictrl_1hr_te_padj = te_padj)
hyp_response_deseq_4hr<-read_csv(here("output", "translation_categories_4hr.csv"))|>
  dplyr::select(gene_id, te_lfc, te_padj) |>
    rename(sictrl_4hr_te_lfc = te_lfc, sictrl_4hr_te_padj = te_padj)

hyp_response_deseq_24hr<-read_csv(here("output", "translation_categories_24hr.csv"))|>
  dplyr::select(gene_id, te_lfc, te_padj) |>
    rename(sictrl_24hr_te_lfc = te_lfc, sictrl_24hr_te_padj = te_padj)


#3e
hyp_response_deseq_1hr_3e_kd <- read_csv(here("output", "translation_categories_si3e_1hr.csv"))|>
  dplyr::select(gene_id, te_lfc, te_padj) |>
    rename(si3e_1hr_te_lfc = te_lfc, si3e_1hr_te_padj = te_padj)

hyp_response_deseq_4hr_3e_kd<- read_csv(here("output", "translation_categories_si3e_4hr.csv"))|>
  dplyr::select(gene_id, te_lfc, te_padj) |>
      rename(si3e_4hr_te_lfc = te_lfc, si3e_4hr_te_padj = te_padj)

hyp_response_deseq_24hr_3e_kd<- read_csv(here("output", "translation_categories_si3e_24hr.csv"))|>
  dplyr::select(gene_id, te_lfc, te_padj) |>
      rename(si3e_24hr_te_lfc = te_lfc, si3e_24hr_te_padj = te_padj)


#3d
hyp_response_deseq_1hr_3d_kd<- read_csv(here("output", "translation_categories_si3d_1hr.csv"))|>
  dplyr::select(gene_id, te_lfc, te_padj) |>
      rename(si3d_1hr_te_lfc = te_lfc, si3d_1hr_te_padj = te_padj)

hyp_response_deseq_4hr_3d_kd<- read_csv(here("output", "translation_categories_si3d_4hr.csv"))|>
  dplyr::select(gene_id, te_lfc, te_padj) |>
        rename(si3d_4hr_te_lfc = te_lfc, si3d_4hr_te_padj = te_padj)

hyp_response_deseq_24hr_3d_kd<- read_csv(here("output", "translation_categories_si3d_24hr.csv"))|>
  dplyr::select(gene_id, te_lfc, te_padj) |>
        rename(si3d_24hr_te_lfc = te_lfc, si3d_24hr_te_padj = te_padj)


all_hypoxic_response <-hyp_response_deseq_1hr |>
  left_join(hyp_response_deseq_4hr) |>
    left_join(hyp_response_deseq_24hr) |>
    left_join(hyp_response_deseq_1hr_3e_kd) |>
    left_join(hyp_response_deseq_4hr_3e_kd) |>
    left_join(hyp_response_deseq_24hr_3e_kd) |>
    left_join(hyp_response_deseq_1hr_3d_kd) |>
    left_join(hyp_response_deseq_4hr_3d_kd) |>
    left_join(hyp_response_deseq_24hr_3d_kd)



head(all_hypoxic_response)
```




# 1 hr - 3e KD

```{r}

colnames(all_hypoxic_response)

sig_sictrl_1hr <- all_hypoxic_response %>%
  filter(sictrl_1hr_te_padj <0.05) |> 
  filter(sictrl_1hr_te_lfc > 0.5 | sictrl_1hr_te_lfc < -0.5)


#counts sig_sictrl
ctrl_down <- sig_sictrl_1hr %>%
  filter(sictrl_1hr_te_lfc < -0.5) %>%
  nrow()

ctrl_up <- sig_sictrl_1hr %>%
  filter(sictrl_1hr_te_lfc > 0.5) %>%
  nrow()




#counts si3e
si3e_down <- sig_sictrl_1hr %>%
  filter(si3e_1hr_te_lfc < -0.5) %>%
  filter(si3e_1hr_te_padj < 0.05) %>%
  nrow()

si3e_up <- sig_sictrl_1hr %>%
  filter(si3e_1hr_te_lfc > 0.5) %>%
  filter(si3e_1hr_te_padj < 0.05) %>%
  nrow()


# Create summary table (transposed with up/down as rows)
summary_table <- data.frame(
  Direction = c("Up", "Down"),
  `si-CTRL` = c(ctrl_up, ctrl_down),
  `si-eIF3e` = c(si3e_up, si3e_down),
  check.names = FALSE
)

# Create table grob
table_grob <- gridExtra::tableGrob(summary_table, rows = NULL, theme = gridExtra::ttheme_minimal(base_size = 9))

# Create barplot for direction changes
bar_data <- data.frame(
  Condition = rep(c("si-CTRL", "si-eIF3e"), each = 2),
  Direction = rep(c("Up", "Down"), 2),
  Count = c(ctrl_up, ctrl_down, si3e_up, si3e_down)
)
bar_data$Direction <- factor(bar_data$Direction, levels = c("Up", "Down"))

bar_plot_3e_1hr <- ggplot(bar_data, aes(x = Condition, y = Count, fill = Direction)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9), vjust = -0.5, size = 5) +
  scale_fill_manual(values = c("Up" = "#D55E00", "Down" = "#0072B2")) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.15))) +
  theme_prism() +
  theme(legend.position = "right") +
  ggtitle("TE Changes - 1hr si-eIF3e")

bar_plot_3e_1hr
ggsave(filename = here("plots/si3e_1hr_barplot.pdf"), bar_plot_3e_1hr, height = 4, width = 4)

scatter_3e_1hr_plot <- ggplot(data = sig_sictrl_1hr, aes(x = sictrl_1hr_te_lfc, y = si3e_1hr_te_lfc)) +
  ylim(-2,2) +
  xlim(-2,2) +
  geom_hline(yintercept = 0, color = "grey") +
  geom_vline(xintercept = 0, color = "grey") +
  geom_point(alpha=.25) +
  ylab(bquote(Log[2]~"si-eIF3e LFC"~"TE: hypoxia vs normoxia")) +
  xlab(bquote(Log[2]~"si-CTRL LFC"~"TE: hypoxia vs normoxia")) +
    # theme_cowplot(font_size = 9)+
  theme_prism()

scatter_3e_1hr_plot <- ggMarginal(scatter_3e_1hr_plot, type = "histogram",
           xparams = list(binwidth = .1, fill = "grey"),
           yparams = list(binwidth = .1, fill = "#56B4E9")
           )

scatter_3e_1hr_plot

ggsave(filename= here("plots/si3e_1hr_response.pdf"), scatter_3e_1hr_plot, height=4, width=4)



```




# 1 hr - 3d KD

```{r}

colnames(all_hypoxic_response)

sig_sictrl_1hr <- all_hypoxic_response %>%
  filter(sictrl_1hr_te_padj <0.05) |>
  filter(sictrl_1hr_te_lfc > 0.5 | sictrl_1hr_te_lfc < -0.5)


#counts sig_sictrl
ctrl_down <- sig_sictrl_1hr %>%
  filter(sictrl_1hr_te_lfc < -0.5) %>%
  nrow()

ctrl_up <- sig_sictrl_1hr %>%
  filter(sictrl_1hr_te_lfc > 0.5) %>%
  nrow()




#counts si3d
si3d_down <- sig_sictrl_1hr %>%
  filter(si3d_1hr_te_lfc < -0.5) %>%
  filter(si3d_1hr_te_padj < 0.05) %>%
  nrow()

si3d_up <- sig_sictrl_1hr %>%
  filter(si3d_1hr_te_lfc > 0.5) %>%
  filter(si3d_1hr_te_padj < 0.05) %>%
  nrow()


# Create summary table (transposed with up/down as rows)
summary_table <- data.frame(
  Direction = c("Up", "Down"),
  `si-CTRL` = c(ctrl_up, ctrl_down),
  `si-eIF3d` = c(si3d_up, si3d_down),
  check.names = FALSE
)

# Create table grob
table_grob <- gridExtra::tableGrob(summary_table, rows = NULL, theme = gridExtra::ttheme_minimal(base_size = 9))

# Create barplot for direction changes
bar_data <- data.frame(
  Condition = rep(c("si-CTRL", "si-eIF3d"), each = 2),
  Direction = rep(c("Up", "Down"), 2),
  Count = c(ctrl_up, ctrl_down, si3d_up, si3d_down)
)
bar_data$Direction <- factor(bar_data$Direction, levels = c("Up", "Down"))

bar_plot_3d_1hr <- ggplot(bar_data, aes(x = Condition, y = Count, fill = Direction)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9), vjust = -0.5, size = 5) +
  scale_fill_manual(values = c("Up" = "#D55E00", "Down" = "#0072B2")) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.15))) +
  theme_prism() +
  theme(legend.position = "right") +
  ggtitle("TE Changes - 1hr si-eIF3d")

bar_plot_3d_1hr
ggsave(filename = here("plots/si3d_1hr_barplot.pdf"), bar_plot_3d_1hr, height = 4, width = 4)

scatter_3d_1hr_plot <- ggplot(data = sig_sictrl_1hr, aes(x = sictrl_1hr_te_lfc, y = si3d_1hr_te_lfc)) +
  ylim(-2,2) +
  xlim(-2,2) +
  geom_hline(yintercept = 0, color = "grey") +
  geom_vline(xintercept = 0, color = "grey") +
  geom_point(alpha=.25) +
  ylab(bquote(Log[2]~"si-eIF3d LFC"~"TE: hypoxia vs normoxia")) +
  xlab(bquote(Log[2]~"si-CTRL LFC"~"TE: hypoxia vs normoxia")) +
    # theme_cowplot(font_size = 9)+
  theme_prism()

scatter_3d_1hr_plot <- ggMarginal(scatter_3d_1hr_plot, type = "histogram",
           xparams = list(binwidth = .1, fill = "grey"),
           yparams = list(binwidth = .1, fill = "#E69F00")
           )

scatter_3d_1hr_plot

ggsave(filename= here("plots/si3d_1hr_response.pdf"), scatter_3d_1hr_plot, height=4, width=4)



```


# 4 hr - 3e KD

```{r}

colnames(all_hypoxic_response)

sig_sictrl_4hr <- all_hypoxic_response %>%
  filter(sictrl_4hr_te_padj <0.05) |>
  filter(sictrl_4hr_te_lfc > 0.5 | sictrl_4hr_te_lfc < -0.5)


#counts sig_sictrl
ctrl_down <- sig_sictrl_4hr %>%
  filter(sictrl_4hr_te_lfc < -0.5) %>%
  nrow()

ctrl_up <- sig_sictrl_4hr %>%
  filter(sictrl_4hr_te_lfc > 0.5) %>%
  nrow()




#counts si3e
si3e_down <- sig_sictrl_4hr %>%
  filter(si3e_4hr_te_lfc < -0.5) %>%
  filter(si3e_4hr_te_padj < 0.05) %>%
  nrow()

si3e_up <- sig_sictrl_4hr %>%
  filter(si3e_4hr_te_lfc > 0.5) %>%
  filter(si3e_4hr_te_padj < 0.05) %>%
  nrow()


# Create summary table (transposed with up/down as rows)
summary_table <- data.frame(
  Direction = c("Up", "Down"),
  `si-CTRL` = c(ctrl_up, ctrl_down),
  `si-eIF3e` = c(si3e_up, si3e_down),
  check.names = FALSE
)

# Create table grob
table_grob <- gridExtra::tableGrob(summary_table, rows = NULL, theme = gridExtra::ttheme_minimal(base_size = 9))

# Create barplot for direction changes
bar_data <- data.frame(
  Condition = rep(c("si-CTRL", "si-eIF3e"), each = 2),
  Direction = rep(c("Up", "Down"), 2),
  Count = c(ctrl_up, ctrl_down, si3e_up, si3e_down)
)
bar_data$Direction <- factor(bar_data$Direction, levels = c("Up", "Down"))

bar_plot_3e_4hr <- ggplot(bar_data, aes(x = Condition, y = Count, fill = Direction)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9), vjust = -0.5, size = 5) +
  scale_fill_manual(values = c("Up" = "#D55E00", "Down" = "#0072B2")) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.15))) +
  theme_prism() +
  theme(legend.position = "right") +
  ggtitle("TE Changes - 4hr si-eIF3e")

bar_plot_3e_4hr
ggsave(filename = here("plots/si3e_4hr_barplot.pdf"), bar_plot_3e_4hr, height = 4, width = 4)

scatter_3e_4hr_plot <- ggplot(data = sig_sictrl_4hr, aes(x = sictrl_4hr_te_lfc, y = si3e_4hr_te_lfc)) +
  ylim(-2,2) +
  xlim(-2,2) +
  geom_hline(yintercept = 0, color = "grey") +
  geom_vline(xintercept = 0, color = "grey") +
  geom_point(alpha=.25) +
  ylab(bquote(Log[2]~"si-eIF3e LFC"~"TE: hypoxia vs normoxia")) +
  xlab(bquote(Log[2]~"si-CTRL LFC"~"TE: hypoxia vs normoxia")) +
    # theme_cowplot(font_size = 9)+
  theme_prism()

scatter_3e_4hr_plot <- ggMarginal(scatter_3e_4hr_plot, type = "histogram",
           xparams = list(binwidth = .1, fill = "grey"),
           yparams = list(binwidth = .1, fill = "#56B4E9")
           )

scatter_3e_4hr_plot

ggsave(filename= here("plots/si3e_4hr_response.pdf"), scatter_3e_4hr_plot, height=4, width=4)



```




# 4 hr - 3d KD

```{r}

colnames(all_hypoxic_response)

sig_sictrl_4hr <- all_hypoxic_response %>%
  filter(sictrl_4hr_te_padj <0.05) |>
  filter(sictrl_4hr_te_lfc > 0.5 | sictrl_4hr_te_lfc < -0.5)


#counts sig_sictrl
ctrl_down <- sig_sictrl_4hr %>%
  filter(sictrl_4hr_te_lfc < -0.5) %>%
  nrow()

ctrl_up <- sig_sictrl_4hr %>%
  filter(sictrl_4hr_te_lfc > 0.5) %>%
  nrow()




#counts si3d
si3d_down <- sig_sictrl_4hr %>%
  filter(si3d_4hr_te_lfc < -0.5) %>%
  filter(si3d_4hr_te_padj < 0.05) %>%
  nrow()

si3d_up <- sig_sictrl_4hr %>%
  filter(si3d_4hr_te_lfc > 0.5) %>%
  filter(si3d_4hr_te_padj < 0.05) %>%
  nrow()


# Create summary table (transposed with up/down as rows)
summary_table <- data.frame(
  Direction = c("Up", "Down"),
  `si-CTRL` = c(ctrl_up, ctrl_down),
  `si-eIF3d` = c(si3d_up, si3d_down),
  check.names = FALSE
)

# Create table grob
table_grob <- gridExtra::tableGrob(summary_table, rows = NULL, theme = gridExtra::ttheme_minimal(base_size = 9))

# Create barplot for direction changes
bar_data <- data.frame(
  Condition = rep(c("si-CTRL", "si-eIF3d"), each = 2),
  Direction = rep(c("Up", "Down"), 2),
  Count = c(ctrl_up, ctrl_down, si3d_up, si3d_down)
)
bar_data$Direction <- factor(bar_data$Direction, levels = c("Up", "Down"))

bar_plot_3d_4hr <- ggplot(bar_data, aes(x = Condition, y = Count, fill = Direction)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9), vjust = -0.5, size = 5) +
  scale_fill_manual(values = c("Up" = "#D55E00", "Down" = "#0072B2")) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.15))) +
  theme_prism() +
  theme(legend.position = "right") +
  ggtitle("TE Changes - 4hr si-eIF3d")

bar_plot_3d_4hr
ggsave(filename = here("plots/si3d_4hr_barplot.pdf"), bar_plot_3d_4hr, height = 4, width = 4)

scatter_3d_4hr_plot <- ggplot(data = sig_sictrl_4hr, aes(x = sictrl_4hr_te_lfc, y = si3d_4hr_te_lfc)) +
  ylim(-2,2) +
  xlim(-2,2) +
  geom_hline(yintercept = 0, color = "grey") +
  geom_vline(xintercept = 0, color = "grey") +
  geom_point(alpha=.25) +
  ylab(bquote(Log[2]~"si-eIF3d LFC"~"TE: hypoxia vs normoxia")) +
  xlab(bquote(Log[2]~"si-CTRL LFC"~"TE: hypoxia vs normoxia")) +
    # theme_cowplot(font_size = 9)+
  theme_prism()

scatter_3d_4hr_plot <- ggMarginal(scatter_3d_4hr_plot, type = "histogram",
           xparams = list(binwidth = .1, fill = "grey"),
           yparams = list(binwidth = .1, fill = "#E69F00")
           )

scatter_3d_4hr_plot

ggsave(filename= here("plots/si3d_4hr_response.pdf"), scatter_3d_4hr_plot, height=4, width=4)



```


# 24 hr - 3e KD

```{r}

colnames(all_hypoxic_response)

sig_sictrl_24hr <- all_hypoxic_response %>%
  filter(sictrl_24hr_te_padj <0.05) |>
  filter(sictrl_24hr_te_lfc > 0.5 | sictrl_24hr_te_lfc < -0.5)


#counts sig_sictrl
ctrl_down <- sig_sictrl_24hr %>%
  filter(sictrl_24hr_te_lfc < -0.5) %>%
  nrow()

ctrl_up <- sig_sictrl_24hr %>%
  filter(sictrl_24hr_te_lfc > 0.5) %>%
  nrow()




#counts si3e
si3e_down <- sig_sictrl_24hr %>%
  filter(si3e_24hr_te_lfc < -0.5) %>%
  filter(si3e_24hr_te_padj < 0.05) %>%
  nrow()

si3e_up <- sig_sictrl_24hr %>%
  filter(si3e_24hr_te_lfc > 0.5) %>%
  filter(si3e_24hr_te_padj < 0.05) %>%
  nrow()


# Create summary table (transposed with up/down as rows)
summary_table <- data.frame(
  Direction = c("Up", "Down"),
  `si-CTRL` = c(ctrl_up, ctrl_down),
  `si-eIF3e` = c(si3e_up, si3e_down),
  check.names = FALSE
)

# Create table grob
table_grob <- gridExtra::tableGrob(summary_table, rows = NULL, theme = gridExtra::ttheme_minimal(base_size = 9))

# Create barplot for direction changes
bar_data <- data.frame(
  Condition = rep(c("si-CTRL", "si-eIF3e"), each = 2),
  Direction = rep(c("Up", "Down"), 2),
  Count = c(ctrl_up, ctrl_down, si3e_up, si3e_down)
)
bar_data$Direction <- factor(bar_data$Direction, levels = c("Up", "Down"))

bar_plot_3e_24hr <- ggplot(bar_data, aes(x = Condition, y = Count, fill = Direction)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9), vjust = -0.5, size = 5) +
  scale_fill_manual(values = c("Up" = "#D55E00", "Down" = "#0072B2")) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.15))) +
  theme_prism() +
  theme(legend.position = "right") +
  ggtitle("TE Changes - 24hr si-eIF3e")

bar_plot_3e_24hr
ggsave(filename = here("plots/si3e_24hr_barplot.pdf"), bar_plot_3e_24hr, height = 4, width = 4)

scatter_3e_24hr_plot <- ggplot(data = sig_sictrl_24hr, aes(x = sictrl_24hr_te_lfc, y = si3e_24hr_te_lfc)) +
  ylim(-2,2) +
  xlim(-2,2) +
  geom_hline(yintercept = 0, color = "grey") +
  geom_vline(xintercept = 0, color = "grey") +
  geom_point(alpha=.25) +
  ylab(bquote(Log[2]~"si-eIF3e LFC"~"TE: hypoxia vs normoxia")) +
  xlab(bquote(Log[2]~"si-CTRL LFC"~"TE: hypoxia vs normoxia")) +
    # theme_cowplot(font_size = 9)+
  theme_prism()

scatter_3e_24hr_plot <- ggMarginal(scatter_3e_24hr_plot, type = "histogram",
           xparams = list(binwidth = .1, fill = "grey"),
           yparams = list(binwidth = .1, fill = "#56B4E9")
           )

scatter_3e_24hr_plot

ggsave(filename= here("plots/si3e_24hr_response.pdf"), scatter_3e_24hr_plot, height=4, width=4)



```




# 24 hr - 3d KD

```{r}

colnames(all_hypoxic_response)

sig_sictrl_24hr <- all_hypoxic_response %>%
  filter(sictrl_24hr_te_padj <0.05) |>
  filter(sictrl_24hr_te_lfc > 0.5 | sictrl_24hr_te_lfc < -0.5)


#counts sig_sictrl
ctrl_down <- sig_sictrl_24hr %>%
  filter(sictrl_24hr_te_lfc < -0.5) %>%
  nrow()

ctrl_up <- sig_sictrl_24hr %>%
  filter(sictrl_24hr_te_lfc > 0.5) %>%
  nrow()




#counts si3d
si3d_down <- sig_sictrl_24hr %>%
  filter(si3d_24hr_te_lfc < -0.5) %>%
  filter(si3d_24hr_te_padj < 0.05) %>%
  nrow()

si3d_up <- sig_sictrl_24hr %>%
  filter(si3d_24hr_te_lfc > 0.5) %>%
  filter(si3d_24hr_te_padj < 0.05) %>%
  nrow()


# Create summary table (transposed with up/down as rows)
summary_table <- data.frame(
  Direction = c("Up", "Down"),
  `si-CTRL` = c(ctrl_up, ctrl_down),
  `si-eIF3d` = c(si3d_up, si3d_down),
  check.names = FALSE
)

# Create table grob
table_grob <- gridExtra::tableGrob(summary_table, rows = NULL, theme = gridExtra::ttheme_minimal(base_size = 9))

# Create barplot for direction changes
bar_data <- data.frame(
  Condition = rep(c("si-CTRL", "si-eIF3d"), each = 2),
  Direction = rep(c("Up", "Down"), 2),
  Count = c(ctrl_up, ctrl_down, si3d_up, si3d_down)
)
bar_data$Direction <- factor(bar_data$Direction, levels = c("Up", "Down"))

bar_plot_3d_24hr <- ggplot(bar_data, aes(x = Condition, y = Count, fill = Direction)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9), vjust = -0.5, size = 5) +
  scale_fill_manual(values = c("Up" = "#D55E00", "Down" = "#0072B2")) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.15))) +
  theme_prism() +
  theme(legend.position = "right") +
  ggtitle("TE Changes - 24hr si-eIF3d")

bar_plot_3d_24hr
ggsave(filename = here("plots/si3d_24hr_barplot.pdf"), bar_plot_3d_24hr, height = 4, width = 4)

scatter_3d_24hr_plot <- ggplot(data = sig_sictrl_24hr, aes(x = sictrl_24hr_te_lfc, y = si3d_24hr_te_lfc)) +
  ylim(-2,2) +
  xlim(-2,2) +
  geom_hline(yintercept = 0, color = "grey") +
  geom_vline(xintercept = 0, color = "grey") +
  geom_point(alpha=.25) +
  ylab(bquote(Log[2]~"si-eIF3d LFC"~"TE: hypoxia vs normoxia")) +
  xlab(bquote(Log[2]~"si-CTRL LFC"~"TE: hypoxia vs normoxia")) +
    # theme_cowplot(font_size = 9)+
  theme_prism()

scatter_3d_24hr_plot <- ggMarginal(scatter_3d_24hr_plot, type = "histogram",
           xparams = list(binwidth = .1, fill = "grey"),
           yparams = list(binwidth = .1, fill = "#E69F00")
           )

scatter_3d_24hr_plot

ggsave(filename= here("plots/si3d_24hr_response.pdf"), scatter_3d_24hr_plot, height=4, width=4)



```


# Combined faceted bar plot: eIF3e (top) and eIF3d (bottom) × timepoint

```{r combined-faceted-barplot}

make_bar_counts <- function(df, ctrl_lfc, ctrl_padj, kd_lfc, kd_padj,
                             lfc_cut = 0.5, padj_cut = 0.05) {
  sig <- df %>%
    filter(.data[[ctrl_padj]] < padj_cut,
           abs(.data[[ctrl_lfc]]) > lfc_cut)
  list(
    ctrl_up   = sum(sig[[ctrl_lfc]]  >  lfc_cut, na.rm = TRUE),
    ctrl_down = sum(sig[[ctrl_lfc]]  < -lfc_cut, na.rm = TRUE),
    kd_up     = sum(sig[[kd_lfc]]   >  lfc_cut  & sig[[kd_padj]]  < padj_cut, na.rm = TRUE),
    kd_down   = sum(sig[[kd_lfc]]   < -lfc_cut  & sig[[kd_padj]]  < padj_cut, na.rm = TRUE)
  )
}

e1  <- make_bar_counts(all_hypoxic_response, "sictrl_1hr_te_lfc",  "sictrl_1hr_te_padj",  "si3e_1hr_te_lfc",  "si3e_1hr_te_padj")
e4  <- make_bar_counts(all_hypoxic_response, "sictrl_4hr_te_lfc",  "sictrl_4hr_te_padj",  "si3e_4hr_te_lfc",  "si3e_4hr_te_padj")
e24 <- make_bar_counts(all_hypoxic_response, "sictrl_24hr_te_lfc", "sictrl_24hr_te_padj", "si3e_24hr_te_lfc", "si3e_24hr_te_padj")
d1  <- make_bar_counts(all_hypoxic_response, "sictrl_1hr_te_lfc",  "sictrl_1hr_te_padj",  "si3d_1hr_te_lfc",  "si3d_1hr_te_padj")
d4  <- make_bar_counts(all_hypoxic_response, "sictrl_4hr_te_lfc",  "sictrl_4hr_te_padj",  "si3d_4hr_te_lfc",  "si3d_4hr_te_padj")
d24 <- make_bar_counts(all_hypoxic_response, "sictrl_24hr_te_lfc", "sictrl_24hr_te_padj", "si3d_24hr_te_lfc", "si3d_24hr_te_padj")

make_rows <- function(gene, tp, counts) {
  data.frame(
    Gene      = gene,
    Timepoint = tp,
    Condition = c("si-CTRL", "si-CTRL", "si-KD", "si-KD"),
    Direction = c("Up", "Down", "Up", "Down"),
    Count     = c(counts$ctrl_up, counts$ctrl_down, counts$kd_up, counts$kd_down)
  )
}

combined_data <- bind_rows(
  make_rows("eIF3e", "1hr",  e1),
  make_rows("eIF3e", "4hr",  e4),
  make_rows("eIF3e", "24hr", e24),
  make_rows("eIF3d", "1hr",  d1),
  make_rows("eIF3d", "4hr",  d4),
  make_rows("eIF3d", "24hr", d24)
) %>%
  mutate(
    Gene      = factor(Gene,      levels = c("eIF3e", "eIF3d")),
    Timepoint = factor(Timepoint, levels = c("1hr", "4hr", "24hr")),
    Direction = factor(Direction, levels = c("Up", "Down")),
    Condition = factor(Condition, levels = c("si-CTRL", "si-KD"))
  )

p_combined <- ggplot(combined_data, aes(x = Condition, y = Count, fill = Direction)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9),
            vjust = -0.5, size = 5) +
  scale_fill_manual(values = c("Up" = "#D55E00", "Down" = "#0072B2")) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.15))) +
  facet_wrap(~ Gene + Timepoint, scales = "free_y", nrow = 2) +
  theme_prism(base_size = 16) +
  theme(legend.position = "right",
        strip.text = element_text(size = 16),
        axis.text  = element_text(size = 14),
        axis.title = element_text(size = 16),
        legend.text  = element_text(size = 14),
        legend.title = element_text(size = 16),
        plot.title    = element_text(size = 18),
        plot.subtitle = element_text(size = 13)) +
  labs(title = "TE Changes: Hypoxic Response and Effect of eIF3 Knockdown",
       subtitle = "padj < 0.05, |LFC| > 0.5 | si-KD counts within si-CTRL significant genes",
       x = "Condition", y = "Count")

p_combined
ggsave(here("plots/te_changes_combined_eif3_hypoxia.pdf"), p_combined,
       width = 10, height = 7)

p_3e <- ggplot(combined_data %>% filter(Gene == "eIF3e"),
               aes(x = Condition, y = Count, fill = Direction)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9),
            vjust = -0.5, size = 5) +
  scale_fill_manual(values = c("Up" = "#D55E00", "Down" = "#0072B2")) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.15))) +
  facet_wrap(~ Timepoint, scales = "free_y", nrow = 1) +
  theme_prism(base_size = 16) +
  theme(legend.position = "right",
        strip.text    = element_text(size = 16),
        axis.text     = element_text(size = 14),
        axis.title    = element_text(size = 16),
        legend.text   = element_text(size = 14),
        legend.title  = element_text(size = 16),
        plot.title    = element_text(size = 18),
        plot.subtitle = element_text(size = 13)) +
  labs(title = "TE Changes: eIF3e Knockdown Hypoxic Response",
       subtitle = "padj < 0.05, |LFC| > 0.5 | si-KD counts within si-CTRL significant genes",
       x = "Condition", y = "Count")

p_3e
ggsave(here("plots/te_changes_eif3e_hypoxia.pdf"), p_3e, width = 10, height = 4)

p_3d <- ggplot(combined_data %>% filter(Gene == "eIF3d"),
               aes(x = Condition, y = Count, fill = Direction)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9),
            vjust = -0.5, size = 5) +
  scale_fill_manual(values = c("Up" = "#D55E00", "Down" = "#0072B2")) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.15))) +
  facet_wrap(~ Timepoint, scales = "free_y", nrow = 1) +
  theme_prism(base_size = 16) +
  theme(legend.position = "right",
        strip.text    = element_text(size = 16),
        axis.text     = element_text(size = 14),
        axis.title    = element_text(size = 16),
        legend.text   = element_text(size = 14),
        legend.title  = element_text(size = 16),
        plot.title    = element_text(size = 18),
        plot.subtitle = element_text(size = 13)) +
  labs(title = "TE Changes: eIF3d Knockdown Hypoxic Response",
       subtitle = "padj < 0.05, |LFC| > 0.5 | si-KD counts within si-CTRL significant genes",
       x = "Condition", y = "Count")

p_3d
ggsave(here("plots/te_changes_eif3d_hypoxia.pdf"), p_3d, width = 10, height = 4)

```
