---
title: "ORFquant Analysis: uORF Detection in Normoxia siCTRL"
author: "Kate"
date: "`r Sys.Date()`"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Load Libraries

```{r load_libraries}
library(here)
library(tidyverse)
library(GenomicRanges)
library(DT)
```

## Load ORFquant Result

```{r load_orfquant}
ORFquant_results <- here("cluster_scripts", "orfquant_output",
                    "normoxia_siCTRL_RiboSeq_1h_final_ORFquant_results")

```

```{r}
load(ORFquant_results)

orfquant_minimal <- data.frame(
id = ORFquant_results$ORFs_tx$ORF_id_tr,
AA = ORFquant_results$ORFs_tx$Protein,
annotation = ORFquant_results$ORFs_tx$ORF_category_Tx,
gene = ORFquant_results$ORFs_tx$gene_id, transcript_id = ORFquant_results$ORFs_tx$transcript_id
)

data <- orfquant_minimal %>% dplyr::select(annotation) %>% table()

annot <- orfquant_minimal %>% dplyr::select(annotation)


# annot <- as.data.frame(data)


ggplot(annot, aes(x= annotation, fill=annotation))+
  geom_histogram(aes(x=annotation), stat="count", show.legend=FALSE)+
  theme_cowplot()+
  coord_flip()+
    geom_text(aes(label = ..count..), stat = "count", nudge_y = 500, colour = "black")

```

## Per-gene ORF type summary

```{r per_gene_orf_summary}
gene_orf_types <- orfquant_minimal %>%
  distinct(gene, annotation) %>%
  mutate(present = 1L) %>%
  pivot_wider(
    names_from = annotation,
    values_from = present,
    values_fill = 0L,
    names_prefix = "orfquant_"
  )

DT::datatable(gene_orf_types, filter = "top")
```

## Export CSV

```{r export_csv}
gene_orf_types_export <- gene_orf_types %>%
  mutate(gene_id_clean = sub("\\.\\d+$", "", gene)) %>%
  select(gene_id_clean, starts_with("orfquant_"))

write_csv(
  gene_orf_types_export,
  here("output", "predictive_modeling", "orfquant_orf_types_normoxia_siCTRL.csv")
)
```
