---
title: "timecourse 231"
author: "Kate"
date: "2025-11_20"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(here)
library(janitor)
library(tximport)
library(tidyverse)
library(EnhancedVolcano)
library(msigdbr)
library(viridis)
library(gridExtra)
library(ggthemes)
library(ggrepel)
library(scales)
library(survival)
library(DESeq2)
library(limma)
library(clusterProfiler)
library(plotly)
library(ggokabeito)
library(ggvenn)
library(ggpubr)
library(DT)
library(edgeR)
library(cowplot)
library(ggExtra)
library(ggprism)
library(GeneOverlap)
library(writexl)
library(survminer)
library(readxl)
library(reshape2)
```
# Functions

```{r}


createNormMatrix <- function(allCounts, spikein = NULL, keepSpikes = NULL) {
  # 1) coerce & round base counts
  allCounts <- round(as.matrix(allCounts), 0)

  # 2) detect empty/absent spike-ins
  has_spike <- !is.null(spikein) &&
               ((is.matrix(spikein) || is.data.frame(spikein)) && nrow(spikein) > 0)

  if (has_spike) {
    spikein <- round(as.matrix(spikein), 0)

    # ensure sample columns align
    if (!identical(colnames(allCounts), colnames(spikein))) {
      if (!all(colnames(allCounts) %in% colnames(spikein)))
        stop("spikein is missing some sample columns found in allCounts.")
      spikein <- spikein[, colnames(allCounts), drop = FALSE]
    }

    # combine human + spike-ins (rows)
    counts_all <- rbind(allCounts, spikein)

    # indices of spike-in rows, if provided
    Spikeindices <- if (!is.null(keepSpikes) && length(keepSpikes) > 0) {
      which(rownames(counts_all) %in% keepSpikes)
    } else {
      NULL
    }
  } else {
    # no spike-ins: use human-only counts and default normalization
    counts_all   <- allCounts
    Spikeindices <- NULL
  }

  # 3) sample metadata (kept as close to yours as possible)
  sample_info <- metadata %>%
    dplyr::select(type, tx, rep, cell) %>%
    unique()
  colnames(sample_info) <- c("SeqType","Condition","Batch","Cell")
  sample_info$Condition <- stats::relevel(as.factor(sample_info$Condition), ref = "CTRL")
  sample_info$SeqType   <- stats::relevel(as.factor(sample_info$SeqType),   ref = "rna")
  # (DESeq2 will set rownames(colData) to colnames(counts_all) if they’re NULL)

  # 4) DESeq2 object + size factors
  dds <- DESeq2::DESeqDataSetFromMatrix(
    countData = counts_all,
    colData   = sample_info,
    design    = ~ Condition + SeqType + Condition:SeqType
  )

  # IMPORTANT: default = median-ratio (no poscounts)
  if (is.null(Spikeindices) || length(Spikeindices) == 0) {
    dds <- DESeq2::estimateSizeFactors(dds)  # type="ratio" by default
  } else {
    dds <- DESeq2::estimateSizeFactors(dds, controlGenes = Spikeindices)  # still "ratio"
  }

  # 5) normalized counts (DESeq2 normalization, not CPM)
  norm <- DESeq2::counts(dds, normalized = TRUE)

  plotData <- norm %>%
    as.data.frame() %>%
    tibble::rownames_to_column(var = "gene_id") %>%
    dplyr::inner_join(gene_symbol, .)

  return(norm)
}

```
# Initial QC

```{r}

ribo <- read_csv(file = "2025_MDAcells_riboseq/QC_summary_ribo.csv") %>% select(Library_ID, Total_Reads_Start,Percent_Original_Reads_Used, "Frags_Mapped")

colnames(ribo) <- c("id","reads","percent_reads_used", "frags_mapped")

# total_ribo_reads_used <- ribo |> 
#     mutate(total_reads_used = reads * (percent_reads_used*.01))



ribo_long <- reshape2::melt(ribo, variable.name = "stage")

p_ribo_reads <- ggbarplot(data = ribo_long |> filter(stage != "percent_reads_used") , x = "id", y = "value", position = position_dodge()) +
  ylab("ribo-seq reads") +
  theme_prism() +
  rotate_x_text(angle = 90) +
scale_y_log10(breaks = 10^seq(1:8), labels = c("10", "100", "1K", "10K", "100K", "1M", "10M", "100M")) +
annotate("rect", ymin = 10^7, ymax = Inf, xmin = 0, xmax = Inf, fill = "green", alpha = 0.2) +
annotate("rect", ymin = 10^6, ymax = 10^7, xmin = 0, xmax = Inf, fill = "orange", alpha = 0.2) + 
annotate("rect", ymin = 0, ymax = 10^6, xmin = 0, xmax = Inf, fill = "red", alpha = 0.2)


p_ribo_reads + ggtitle("ribo-seq reads")
ggsave(here("plots/riboseq_reads.png"), width=11, height = 5)

p_ribo_percent <- ggbarplot(data = ribo_long |> filter(stage == "percent_reads_used") , x = "id", y = "value", position = position_dodge()) + 
  ylab("% ribo-seq reads") +
  theme_prism() +
  rotate_x_text(angle = 90) +
  annotate("rect", ymin = 20, ymax = Inf, xmin = 0, xmax = Inf, fill = "green", alpha = 0.2) + 
    annotate("rect", ymin = 0, ymax = 20, xmin = 0, xmax = Inf, fill = "red", alpha = 0.2)


p_ribo_percent + ggtitle("ribo-seq % used")
ggsave(here("plots/riboseq_percent.png"), width=11, height = 5)



# reads into salmon

p_ribo_reads_salmon <- ggbarplot(data = ribo_long |> filter(stage == "frags_mapped") , x = "id", y = "value", position = position_dodge()) +
  ylab("ribo-seq reads into salmon") +
  theme_prism() +
  rotate_x_text(angle = 90) +
scale_y_log10(breaks = 10^seq(1:8), labels = c("10", "100", "1K", "10K", "100K", "1M", "10M", "100M")) 
# +
# annotate("rect", ymin = 10^7, ymax = Inf, xmin = 0, xmax = Inf, fill = "green", alpha = 0.2) +
# annotate("rect", ymin = 10^6, ymax = 10^7, xmin = 0, xmax = Inf, fill = "orange", alpha = 0.2) + 
# annotate("rect", ymin = 0, ymax = 10^6, xmin = 0, xmax = Inf, fill = "red", alpha = 0.2)


p_ribo_reads_salmon + ggtitle("frags_mapped")
ggsave(here("plots/ribo_seq_frags_mapped.png"), width=11, height = 5)


```

```{r}

rna <- read_csv(file = "2025_MDAcells_riboseq/QC_summary_rna.csv") %>% select(Library_ID, Total_Reads_Start, Percent_Original_Reads_Used)

colnames(rna) <- c("id","reads","percent_reads_used")

rna_long <- reshape2::melt(rna, variable.name = "stage")

p_rna_reads <- ggbarplot(data = rna_long |> filter(stage != "percent_reads_used") , x = "id", y = "value", position = position_dodge()) +
  ylab("rna-seq reads") +
  theme_prism() +
  rotate_x_text(angle = 90) +
scale_y_log10(breaks = 10^seq(1:8), labels = c("10", "100", "1K", "10K", "100K", "1M", "10M", "100M")) +
annotate("rect", ymin = 10^7, ymax = Inf, xmin = 0, xmax = Inf, fill = "green", alpha = 0.2) +
annotate("rect", ymin = 10^6, ymax = 10^7, xmin = 0, xmax = Inf, fill = "orange", alpha = 0.2) + 
annotate("rect", ymin = 0, ymax = 10^6, xmin = 0, xmax = Inf, fill = "red", alpha = 0.2)

p_rna_reads + ggtitle("rna-seq reads")
ggsave(here("plots/rnaseq_reads.png"), width=11, height = 5)


p_rna_percent <- ggbarplot(data = rna_long |> filter(stage == "percent_reads_used") , x = "id", y = "value", position = position_dodge()) + 
  ylab("% rna-seq reads") +
  theme_prism() +
  rotate_x_text(angle = 90) +
  annotate("rect", ymin = 70, ymax = Inf, xmin = 0, xmax = Inf, fill = "green", alpha = 0.2) +
  annotate("rect", ymin = 50, ymax = 70, xmin = 0, xmax = Inf, fill = "orange", alpha = 0.2) + 
  annotate("rect", ymin = 0, ymax = 50, xmin = 0, xmax = Inf, fill = "red", alpha = 0.2)


p_rna_percent + ggtitle("rna-seq % used")
ggsave(here("plots/rnaseq_percent.png"), width=11, height = 5)




```


```{r}
si3e_col = "#56B4E9"
si3d_col = "#E69F00"
```

## Load transcript-level data

Importing metadata and all salmon counts
```{r meta data}
metadata <- read_csv(here("accessories","metadata_231_timecourse.csv"), skip = 0) %>% 
  clean_names()

head(metadata)
unique(metadata$type)

metadata <- metadata |>
  rename(library = `type`)


metadata <- metadata |>
  dplyr::mutate(type = dplyr::recode(library,
                                      "RiboSeq"="ribo")) |> 
                                          dplyr::mutate(library = dplyr::recode(type,
                                      "Input_Ribo_RNAseq"="rna"))

#ribosome lysate = ribosome seq
#rRNA depletion = RNA seq
#rename variables remove outlier

#edit factor levels
metadata$library <- relevel(x = factor(metadata$library), ref = "rna")

metadata$treatment <- relevel(x = factor(metadata$treatment), ref = "siCTRL")
metadata$treatment <- recode(metadata$treatment, "siCTRL" = "sictrl")

metadata$condition <- relevel(x = factor(metadata$condition), ref = "normoxia")
metadata$rep <- recode(metadata$rep, RepA = "a", RepB = "b", RepC = "c")

```

```{r import gene info}

#import key on RNA type, remove premRNA
geneInfo <- read_tsv(here("accessories", "human","gene_anno_hs_dm_v49_r111.tsv.gz"), col_names = F) 
head(geneInfo)
colnames(geneInfo) <- c("gene_id","symbol","biotype","species", "version")

geneInfo <- geneInfo %>%
  filter(!str_detect(biotype, "pre_"))


tx2gene <- read_tsv(here("accessories/human/tx2gene_hs_dm_v49_r111.tsv.gz"), col_names="FALSE")
colnames(tx2gene) <- c("transcript", "gene")

#import transcripts for gene to transcript mapping

gene_symbol <- geneInfo %>% dplyr::select(gene_id, symbol) %>% unique()

# Check for duplicate gene_ids
duplicate_genes <- gene_symbol %>%
  group_by(gene_id) %>%
  filter(n() > 1) %>%
  arrange(gene_id)

if(nrow(duplicate_genes) > 0) {
  cat("Found", nrow(duplicate_genes), "duplicate gene_id entries in gene_symbol:\n")
  print(duplicate_genes)
  # Keep only first occurrence of each gene_id
  gene_symbol <- gene_symbol %>%
    distinct(gene_id, .keep_all = TRUE)
  cat("After removing duplicates: Total genes:", nrow(gene_symbol), "\n")
} else {
  cat("No duplicate gene_ids found in gene_symbol\n")
}

# Verify gene_symbol has unique gene_ids
cat("Total genes in gene_symbol:", nrow(gene_symbol), "\n")
cat("Unique gene_ids:", length(unique(gene_symbol$gene_id)), "\n")

```

```{r txi import, include=FALSE}
#name files to import
myquantfiles <- paste(here(), "/2025_MDAcells_riboseq/salmon/",
                      metadata$id,
                      "/quant.sf.gz",
                      sep = "")

names(myquantfiles) <- paste(metadata$condition, metadata$treatment, metadata$hours, metadata$rep, metadata$library, metadata$id, sep = "_")

#import salmon files
myTxi <- tximport(myquantfiles, type = "salmon", tx2gene = tx2gene)

# Check for duplicate rownames in counts
cat("Rows in myTxi$counts:", nrow(myTxi$counts), "\n")
cat("Unique rownames:", length(unique(rownames(myTxi$counts))), "\n")

if(any(duplicated(rownames(myTxi$counts)))) {
  dup_genes <- rownames(myTxi$counts)[duplicated(rownames(myTxi$counts))]
  cat("WARNING: Found", length(dup_genes), "duplicate gene IDs in myTxi$counts:\n")
  print(head(dup_genes, 20))
}
```

separate out human and dros genes


```{r}
#separate dros and human counts
counts <- myTxi$counts
  
is_dros <- grepl("^FB", rownames(counts))   

cts_dros  <- counts[ is_dros, , drop = FALSE] # <- keep for separate heatmap
cts_human <- counts[!is_dros, , drop = FALSE]


# Look at distribution of sum of counts
# to determine threshold for calling gene expressed
hist(log2(rowSums(cts_human)), breaks = 60) 


keepGenes <- rownames(cts_human[log2(rowSums(cts_human)) > 11,])


pc <-geneInfo %>%
  filter(biotype =="protein_coding") %>% 
  pull(gene_id) %>% 
  unique()

pc_keep <- pc[pc %in% keepGenes]

nonpolyA <- readxl::read_xlsx(path = here("accessories","polyAminus.xlsx"), sheet = 1) %>% 
   pull(Gene)


nonpolyA_ID <- geneInfo %>%
  filter(symbol %in% nonpolyA) %>% 
  pull(gene_id) %>% 
  unique()

shortgenes <- read_csv(here("accessories", "human", "short_genes_under_200nt_human_v49.csv.zip")) %>% pull(gene_id)
#Neel requests that we remove short genes! 


# retrieve counts from the myTxi and remove noncoding and non-pA genes
#NOTE: Neel requests that we only remove the non-pA genes and keep annotation open. 

allCounts <- cts_human %>%
  as.data.frame() %>%
  rownames_to_column(var = "gene") %>%
  filter(gene %in% keepGenes) %>%
  filter(!gene %in% nonpolyA_ID) %>%
  filter(!gene %in% shortgenes) %>%
  column_to_rownames(var = "gene") %>%
  as.matrix() %>%
  round(.,0)

# Comprehensive check for rowname issues in allCounts
cat("\n=== Checking allCounts rownames ===\n")
cat("Rows in allCounts:", nrow(allCounts), "\n")
cat("Unique rownames:", length(unique(rownames(allCounts))), "\n")

# Check for duplicates
if(any(duplicated(rownames(allCounts)))) {
  dup_genes <- rownames(allCounts)[duplicated(rownames(allCounts))]
  cat("ERROR: Found", length(dup_genes), "duplicate gene IDs:\n")
  print(head(dup_genes, 20))
} else {
  cat("✓ No duplicate rownames\n")
}

# Check for NA values
if(any(is.na(rownames(allCounts)))) {
  cat("ERROR: Found", sum(is.na(rownames(allCounts))), "NA values in rownames\n")
} else {
  cat("✓ No NA values in rownames\n")
}

# Check for empty strings
if(any(rownames(allCounts) == "")) {
  cat("ERROR: Found", sum(rownames(allCounts) == ""), "empty strings in rownames\n")
} else {
  cat("✓ No empty strings in rownames\n")
}

# Check for NULL
if(is.null(rownames(allCounts))) {
  cat("ERROR: rownames are NULL\n")
} else {
  cat("✓ Rownames are not NULL\n")
}

cat("\nFirst 10 rownames:\n")
print(head(rownames(allCounts), 10))

write_csv(as.data.frame(allCounts) %>% rownames_to_column("gene_id"), here("output", "human_allCounts_raw_v49.csv"))


#let's require a protein_coding biotype for dros genes
keepDros <- geneInfo %>% filter(species == "fly") %>% filter(biotype == "protein_coding") %>% pull(gene_id)

cts_dros <- cts_dros[rownames(cts_dros) %in% keepDros, , drop = FALSE]


cts_dros <- cts_dros[rowSums(cts_dros) > 0, ] #let's require non-zero values
#hist(log2(1 + rowSums(cts_dros)), breaks = 60) #won't include now

#We have previously determined that we want to only use the top 500 expressed spikeIn genes. 

top500_ids <- cts_dros %>%
  as.data.frame() %>%                     # matrix -> df
  rownames_to_column("gene_id") %>%       # keep gene IDs
  mutate(total = rowSums(across(-gene_id), na.rm = TRUE)) %>%
  slice_max(total, n = 500, with_ties = FALSE) %>%  # exactly 500
  pull(gene_id)

# subset in that order
spikein <- cts_dros[top500_ids, , drop = FALSE] %>% round(.,0)

write_csv(as.data.frame(spikein) %>% rownames_to_column("gene_id"), here("output", "dros_spikeInCounts_raw_v49.csv"))

## 2) Per-gene mean by library type (RNA vs Ribo)
# Infer from column names:
sample_type <- tibble(
  sample = colnames(spikein),
  type   = ifelse(grepl("ribo", colnames(spikein), ignore.case = TRUE), "ribo", "rna")
)

means_by_type <- as_tibble(spikein, rownames = "gene") %>%
  pivot_longer(-gene, names_to = "sample", values_to = "count") %>%
  left_join(sample_type, by = "sample") %>%
  group_by(gene, type) %>%
  summarize(mean_count = mean(count, na.rm = TRUE), .groups = "drop") %>%
  mutate(mean_log = log10(1 + mean_count))

## 3) Keep only your selected genes and plot
expr_comp_by_type <- means_by_type %>%
  mutate(type  = factor(type,  levels = c("ribo","rna")))

```






```{r}
# visualize distribution of counts
hist_count <- hist(log2(rowSums(myTxi$counts)), breaks = 50)
#determine threshold

#distribution of abundance histogram
#hist_abundance <- hist(log2(rowSums(myTxi$abundance)), breaks = 50)

#only keeping rows with counts  log2> 10 across all samples - want around 10-15k genes - want genes that are highly expressed
keepGenes <- rownames(myTxi$counts[log2(rowSums(myTxi$counts)) > 10 ,])

#removes noise and keeps only highly expressed genes
# results show bimodal distribution
#1 RNA per cell = 1 TPM
```




```{r standard deviation filtering}
# log transforming with pseudocount to avoid undefined numbers
qcinput <- log2(myTxi$abundance[keepGenes,] + 1) 

qcinput <- qcinput[rowSds(qcinput) > 1,] 

dim(qcinput)
```



```{r}

mycor <- cor(qcinput, method = "pearson")

heatmap <- pheatmap::pheatmap(
  mat = mycor,
  border_color = "black",  # Black borders around cells
   #color = colorRampPalette(c("blue", "white", "red"))(100),  # Custom color gradient
   scale = "none",  
  cluster_rows = TRUE,  
  cluster_cols = TRUE,  
  fontsize = 8 
)

heatmap

ggsave(here("plots/qc_all.pdf"), heatmap, width=15, height = 14)
```

# 107 is an outlier

## RNA only

```{r}
qcinput_rna <- qcinput[, grep("rna", colnames(qcinput))]

mycor_rna <- cor(qcinput_rna, method = "pearson")

heatmap_rna <- pheatmap::pheatmap(
  mat = mycor_rna,
  border_color = "black",
  scale = "none",
  cluster_rows = TRUE,
  cluster_cols = TRUE,
  fontsize = 8
)

heatmap_rna
ggsave(here("plots/qc_rna_only.pdf"), heatmap_rna, width=10, height = 9)
```

## Ribo only

```{r}
qcinput_ribo <- qcinput[, grep("ribo", colnames(qcinput))]

mycor_ribo <- cor(qcinput_ribo, method = "pearson")

heatmap_ribo <- pheatmap::pheatmap(
  mat = mycor_ribo,
  border_color = "black",
  scale = "none",
  cluster_rows = TRUE,
  cluster_cols = TRUE,
  fontsize = 8
)

heatmap_ribo
ggsave(here("plots/qc_ribo_only.pdf"), heatmap_ribo, width=10, height = 9)
```

## Ribo only without outlier 107

```{r}
qcinput_ribo_no107 <- qcinput_ribo[, !grepl("0107", colnames(qcinput_ribo))]

mycor_ribo_no107 <- cor(qcinput_ribo_no107, method = "pearson")

heatmap_ribo_no107 <- pheatmap::pheatmap(
  mat = mycor_ribo_no107,
  border_color = "black",
  scale = "none",
  cluster_rows = TRUE,
  cluster_cols = TRUE,
  fontsize = 8
)

heatmap_ribo_no107
ggsave(here("plots/qc_ribo_no107.pdf"), heatmap_ribo_no107, width=10, height = 9)
```
















Split normoxia and hypoxia
```{r}

qc_input_normoxia <- qcinput[, grep("normoxia", colnames(qcinput))]

qc_input_hypoxia <- qcinput[, grep("hypoxia", colnames(qcinput))]

```


# Visualizations

# Figure 1: Normoxia

```{r}
#KDs
mycor_norm <- cor(qc_input_normoxia, method = "pearson")

colnames(mycor_norm) <- gsub("^normoxia_", "", colnames(mycor_norm))  # Remove "normoxia_" prefix
rownames(mycor_norm) <- gsub("^normoxia_", "", rownames(mycor_norm))  # Same for row names

# Replace underscores with spaces
colnames(mycor_norm) <- gsub("_", " ", colnames(mycor_norm))
rownames(mycor_norm) <- gsub("_", " ", rownames(mycor_norm))

# Create the heatmap with the cleaned-up names
heatmap_normoxia <- pheatmap::pheatmap(
  mat = mycor_norm,
  border_color = "black",  # Black borders around cells
   #color = colorRampPalette(c("blue", "white", "red"))(100),  # Custom color gradient
   scale = "none",  
  cluster_rows = TRUE,  
  cluster_cols = TRUE,  
  fontsize = 12 
)


heatmap_normoxia
ggsave(heatmap_normoxia, filename=here("plots/plots_231/heatmap_normoxia.pdf"), width=4.5, height=4)

# RIBO average correlation coefficient

qc_input_normoxia_ribo <- qc_input_normoxia[, grep("ribo", colnames(qc_input_normoxia))]

mycor_ribo_norm <- cor(qc_input_normoxia_ribo, method = "pearson")

# Extract the lower triangular part of the matrix without the diagonal
lower_tri <- mycor_ribo_norm[lower.tri(mycor_ribo_norm, diag=FALSE)]

# Calculate the average correlation coefficient (excluding diagonal)
average_correlation <- mean(lower_tri)

# Print the result
average_correlation


# rna average correlation coefficient

qc_input_normoxia_rna <- qc_input_normoxia[, grep("rna", colnames(qc_input_normoxia))]

mycor_rna_norm <- cor(qc_input_normoxia_rna, method = "pearson")


# Extract the lower triangular part of the matrix without the diagonal
lower_tri <- mycor_rna_norm[lower.tri(mycor_rna_norm, diag=FALSE)]

# Calculate the average correlation coefficient (excluding diagonal)
average_correlation <- mean(lower_tri)

# Print the result
average_correlation

```


# Figure 2: Hypoxia, knockdowns


Heatmap

```{r}
mycor_hyp_kds <- cor(qc_input_hypoxia, method = "pearson")

colnames(mycor_hyp_kds) <- gsub("^hypoxia_", "", colnames(mycor_hyp_kds))  # Remove "hypoxia_" prefix
rownames(mycor_hyp_kds) <- gsub("^hypoxia_", "", rownames(mycor_hyp_kds))  # Same for row names

# Replace underscores with spaces
colnames(mycor_hyp_kds) <- gsub("_", " ", colnames(mycor_hyp_kds))
rownames(mycor_hyp_kds) <- gsub("_", " ", rownames(mycor_hyp_kds))

# Create the heatmap with the cleaned-up names
heatmap_hypoxia <- pheatmap::pheatmap(
  mat = mycor_hyp_kds,
  border_color = "black",  # Black borders around cells
   #color = colorRampPalette(c("blue", "white", "red"))(100),  # Custom color gradient
   scale = "none",  
  cluster_rows = TRUE,  
  cluster_cols = TRUE,  
  fontsize = 12 
)





heatmap_hypoxia
ggsave(heatmap_hypoxia, filename=here("plots/plots_231/heatmap_hyp.pdf"), width=4.5, height=4)

```

```{r}

# RIBO average correlation coefficient

qc_input_hypoxia_ribo <- qc_input_hypoxia[, grep("ribo", colnames(qc_input_hypoxia))]

mycor_ribo_hyp <- cor(qc_input_hypoxia_ribo, method = "pearson")


# Extract the lower triangular part of the matrix without the diagonal
lower_tri <- mycor_ribo_hyp[lower.tri(mycor_ribo_hyp, diag=FALSE)]

# Calculate the average correlation coefficient (excluding diagonal)
average_correlation <- mean(lower_tri)

# Print the result
average_correlation



# rna average correlation coefficient

qc_input_hypoxia_rna <- qc_input_hypoxia[, grep("rna", colnames(qc_input_hypoxia))]

mycor_rna_hyp <- cor(qc_input_hypoxia_rna, method = "pearson")


# Extract the lower triangular part of the matrix without the diagonal
lower_tri <- mycor_rna_hyp[lower.tri(mycor_rna_hyp, diag=FALSE)]

# Calculate the average correlation coefficient (excluding diagonal)
average_correlation <- mean(lower_tri)

# Print the result
average_correlation


```