# Generate FEATURES.md - the feature dictionary for feature_matrix_tco.rds.
#
# Generated, never hand-written. feature_annotation.csv is the source of truth but lives in
# output/, which is gitignored, so the matrix's contents are otherwise invisible to anyone
# reading the repo. This renders it into a committed document.
#
# The verification column is DERIVED, not asserted by hand: it reports which validation chunk
# of 01_build_feature_matrix.Rmd mentions each feature or its family. That keeps it honest -
# a feature with no check shows up as having no check, rather than being quietly assumed fine.
#
# Usage: Rscript code/translational_control_overview/01b_feature_dictionary.R
suppressMessages({library(tidyverse); library(here)})

out_dir <- here("output", "translational_control_overview")
ann <- read_csv(file.path(out_dir, "feature_annotation.csv"), show_col_types = FALSE)
mat <- readRDS(file.path(out_dir, "feature_matrix_tco.rds"))
rmd <- readLines(here("code", "translational_control_overview", "01_build_feature_matrix.Rmd"))

stopifnot("annotation and matrix disagree" = setequal(ann$feature, colnames(mat)))

# --- coverage -------------------------------------------------------------------------
coverage <- map_dbl(ann$feature, function(f) {
  v <- mat[[f]]
  if (is.list(v)) v <- unlist(v)
  mean(!is.na(v))
})
ann$coverage <- round(100 * coverage, 1)

# --- which validation chunk covers each feature ----------------------------------------
# Chunk boundaries, then a feature is "checked" if its name or its family's build variable
# appears inside a validate_* chunk.
starts <- grep("^```\\{r ", rmd)
ends   <- grep("^```$", rmd)
chunks <- map_dfr(starts, function(s) {
  e <- ends[ends > s][1]
  tibble(name = sub("^```\\{r ([^,}]+).*$", "\\1", rmd[s]),
         body = paste(rmd[(s + 1):(e - 1)], collapse = "\n"))
}) %>% filter(str_starts(name, "validate_|reproduce_"))

# Some chunks name a feature directly; others loop over a family's column vector (term_cols,
# g4_cols, pep_cols), so the feature names never appear literally. Both are credited, and
# neither may be credited by accident: a bare substring match gives "transcript_id" credit
# for appearing inside "transcript_id_clean", and gives every id column credit for appearing
# in a join. Direct matches are therefore whole-word, and loop-based coverage is declared.
FAMILY_CHUNKS <- list(
  termination     = "validate_termination",
  g4              = "validate_g4mer",
  nascent_peptide = "validate_peptide",
  polya_track     = "validate_peptide"
)
stopifnot("FAMILY_CHUNKS names a chunk that does not exist" =
            all(unlist(FAMILY_CHUNKS) %in% chunks$name))
stopifnot("FAMILY_CHUNKS names a family that does not exist" =
            all(names(FAMILY_CHUNKS) %in% ann$family))

word_hit <- function(body, f)
  str_detect(body, paste0("(?<![A-Za-z0-9_.])", str_escape(f), "(?![A-Za-z0-9_.])"))

ann$checked_in <- map_chr(seq_len(nrow(ann)), function(i) {
  f   <- ann$feature[i]
  fam <- ann$family[i]
  # Identifiers, labels and QC flags are not features; a check never "covers" them.
  if (ann$block[i] %in% c("id", "label", "outcome", "outcome_derived", "qc",
                          "cds_eligibility")) return("")
  hit <- chunks$name[map_lgl(chunks$body, word_hit, f = f)]
  hit <- setdiff(hit, "reproduce_baseline")     # reproduction is not a correctness check
  if (fam %in% names(FAMILY_CHUNKS)) hit <- union(hit, FAMILY_CHUNKS[[fam]])
  if (length(hit)) paste(sort(sub("^validate_", "", hit)), collapse = ", ") else ""
})

# --- render ----------------------------------------------------------------------------
esc <- function(x) str_replace_all(replace_na(as.character(x), ""), "\\|", "\\\\|")

block_order  <- c("intrinsic", "external", "eif4e", "label", "outcome", "outcome_derived",
                  "qc", "cds_eligibility", "id")
block_notes <- c(
  intrinsic       = "Computable from the transcript sequence alone. These are what transfer to a new dataset.",
  external        = "Measured in some other experiment. Will not exist for most new datasets.",
  eif4e           = "eIF4E-derived, and circular for a 4E model, so kept separable.",
  label           = "The target and anything derived from it. Never a feature.",
  outcome         = "The target. Never a feature.",
  outcome_derived = "Derived from the target. Never a feature.",
  qc              = "Quality flags about whether another feature is meaningful. Not modelled.",
  cds_eligibility = "CDS completeness flags used to mask codon features. Not modelled.",
  id              = "Identifiers."
)

modelled <- ann %>% filter(block %in% c("intrinsic", "external"), !deprecated)

lines <- c(
  "# Feature dictionary: `feature_matrix_tco.rds`",
  "",
  "**Generated by `01b_feature_dictionary.R` - do not edit by hand.**",
  "Regenerate after any change to `01_build_feature_matrix.Rmd`:",
  "",
  "```",
  "Rscript code/translational_control_overview/01b_feature_dictionary.R",
  "```",
  "",
  sprintf("Matrix: **%d transcripts x %d columns**, keyed on `transcript_id_clean`.",
          nrow(mat), ncol(mat)),
  sprintf("Of these, **%d are modelled** by default (blocks `intrinsic` + `external`, excluding deprecated); the rest are identifiers, labels or QC flags.",
          nrow(modelled)),
  "",
  "## How to read the columns",
  "",
  "- **variant** - `single`, or one member of a variant pair (`current` / `corrected`). `02_rf_model.Rmd` takes one member per pair via `variant_set`; both in one forest would split credit between near-duplicates.",
  "- **added_in** - `baseline` means inherited unchanged from `feature_matrix_dhx29_kd_feature.rds`; `tco` means built or corrected in this fork.",
  "- **cov%** - percent of transcripts with a non-NA value. `02_` drops any feature below 50% as sparse, because median imputation manufactures a split between real and imputed values.",
  "- **checks** - which `validate_*` chunk of `01_build_feature_matrix.Rmd` exercises this feature. **Blank means no check in this fork**: for `added_in = baseline` features the checks live in their original `code/predictive_modeling/` notebook, and are not re-run here.",
  "",
  "> **What the checks do and do not establish.** Range checks pass on a scrambled join, and a",
  "> biological spot-check can pass on a wrong input - the `01h_` Kozak PWM bug passed its own",
  "> tier-monotonicity check, because a within-tier error cancels in the tier means. The",
  "> reproduction gates prove this fork computes what notebook 07 computed; they say nothing",
  "> about whether notebook 07 was right. Every bug found in this project so far was found by",
  "> independent reimplementation (`00_feature_reconciliation.Rmd`), not by an assertion.",
  ""
)

for (bl in block_order) {
  sub <- ann %>% filter(block == bl)
  if (!nrow(sub)) next
  lines <- c(lines, sprintf("## Block: `%s` (%d)", bl, nrow(sub)), "",
             block_notes[[bl]], "")
  for (fam in sub %>% count(family, sort = TRUE) %>% pull(family)) {
    fs <- sub %>% filter(family == fam) %>% arrange(feature)
    lines <- c(lines, sprintf("### `%s` (%d)", fam, nrow(fs)), "",
               "| feature | variant | added_in | cov% | definition | checks |",
               "|---|---|---|---|---|---|")
    lines <- c(lines, sprintf("| `%s` | %s | %s | %.1f | %s | %s |",
                              fs$feature, esc(fs$variant), esc(fs$added_in), fs$coverage,
                              esc(fs$definition), esc(fs$checked_in)))
    lines <- c(lines, "")
  }
}

no_check <- modelled %>% filter(checked_in == "")
lines <- c(lines,
  "## Verification coverage",
  "",
  sprintf("| | modelled features |"),
  "|---|---|",
  sprintf("| exercised by a `validate_*` chunk here | %d |", sum(modelled$checked_in != "")),
  sprintf("| no check in this fork | %d |", nrow(no_check)),
  "",
  sprintf("Unchecked here, by family: %s.",
          no_check %>% count(family, sort = TRUE) %>%
            mutate(t = sprintf("`%s` (%d)", family, n)) %>% pull(t) %>%
            paste(collapse = ", ")),
  "",
  "These are inherited features whose checks live in `code/predictive_modeling/`. They are not",
  "unverified, but they are not verified *here*, and the reproduction gate would not notice if",
  "one of them had always been wrong.",
  "")

writeLines(lines, here("code", "translational_control_overview", "FEATURES.md"))
cat("Wrote code/translational_control_overview/FEATURES.md -",
    nrow(ann), "columns,", nrow(modelled), "modelled,",
    sum(modelled$checked_in != ""), "checked here\n")
