#!/usr/bin/env bash
# Build a cell set's own-isoform feature matrix end to end. Stops at the first failed gate.
#   bash code/translational_control_overview/01m_run_celltx_build.sh <hela|dhx29|mane|mcf7six1>
# Inputs already on disk: the transcript map, RNAplfold _lunp files and merged G4mer summaries
# (01k_run_hela_precompute.sh <cell>). Do not edit this file while it is running.
set -u
cd "$(cd "$(dirname "$0")/../.." && pwd)"
CELL="${1:?usage: $0 <hela|dhx29|mane|mcf7six1>}"
case "$CELL" in hela) LINE="HeLa";; dhx29|mane) LINE="HEK293T";; mcf7six1) LINE="MCF7-SIX1";; *) echo "unknown cell"; exit 1;; esac
export RSTUDIO_PANDOC="${RSTUDIO_PANDOC:-/Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools}"
B=code/translational_control_overview/01l_build_celltx_baseline.R
LOG=$(mktemp -d)
say() { echo; echo "=============== $* ==============="; date '+%H:%M:%S'; }
step() {  # step <name> <command...>: run, show the useful lines, stop on failure
  local name="$1"; shift
  "$@" > "$LOG/$name.log" 2>&1; local rc=$?
  grep -vE "built under|^Warning|Attaching|masked|^ *package" "$LOG/$name.log" | tail -25
  [ $rc -eq 0 ] || { echo "FAILED at $name (exit $rc) - full log $LOG/$name.log"; exit 1; }
}
# A stage whose cache already exists is skipped (its gate passed when the cache was written).
cache_of() { case "$1" in seq) echo seqfeat;; struct) echo struct_from_lunp;; csc) echo csc;; *) echo "";; esac; }
for ST in seq struct csc assemble kozak; do
  C=$(cache_of "$ST")
  if [ -n "$C" ] && [ -s "output/predictive_modeling/${CELL}_${C}.rds" ]; then
    say "$CELL baseline: $ST - cached, skipped"; continue
  fi
  say "$CELL baseline: $ST"; step "baseline_$ST" Rscript --vanilla "$B" "$CELL" "$ST"
done
say "$CELL DHX29 occupancy (external feature input for 01_)"
step occupancy Rscript --vanilla code/translational_control_overview/01h_mcf7six1_dhx29_occupancy.R "$CELL"
say "$CELL feature matrix (01_build_feature_matrix.Rmd)"
step matrix Rscript --vanilla -e "rmarkdown::render('code/translational_control_overview/01_build_feature_matrix.Rmd',
  params=list(cell_line='$LINE', baseline_rds='feature_matrix_${CELL}_dhx29_kd_feature.rds',
              kozak_seqs_rds='precomputed_${CELL}_kozak_sequences.rds',
              dhx29_occ_rds='dhx29_riboseq_occupancy_${CELL}.rds', g4mer_tag='_${CELL}',
              cache_tag='_${CELL}', codon_weights_rds='codon_weights_mdamb231.rds',
              out_rds='feature_matrix_tco_${CELL}.rds'),
  output_file='01_build_feature_matrix_${CELL}.html', intermediates_dir='$LOG/km', quiet=TRUE)"
say "$CELL value parity vs MDA-MB-231"
step parity Rscript --vanilla code/translational_control_overview/01n_value_parity_check.R "feature_matrix_tco_${CELL}.rds"
say "$CELL BUILD COMPLETE (logs: $LOG)"
